//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDBSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public string Correo { get; set; }
        public int IdTipoConsulta { get; set; }
        public string TextoConsulta { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual TipoConsulta TipoConsulta { get; set; }
    }
}
